//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2019-10-04 오후 3:10:33
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace PEIU.Models
{

    /// <summary>
    /// VIEW
    /// </summary>
    public partial class VwMinuteEssstat {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for VwMinuteEssstat constructor in the schema.
        /// </summary>
        public VwMinuteEssstat()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ID in the schema.
        /// </summary>
        public virtual int ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SiteId in the schema.
        /// </summary>
        public virtual short? SiteId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Timestamp in the schema.
        /// </summary>
        public virtual System.DateTime Timestamp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SumOfCharging in the schema.
        /// </summary>
        public virtual double? SumOfCharging
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SumOfDischarging in the schema.
        /// </summary>
        public virtual double? SumOfDischarging
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SumOfPvPower in the schema.
        /// </summary>
        public virtual double? SumOfPvPower
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AvgOfSoc in the schema.
        /// </summary>
        public virtual double? AvgOfSoc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AvgOfSoh in the schema.
        /// </summary>
        public virtual double? AvgOfSoh
        {
            get;
            set;
        }
    }

}
