//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2019-10-01 오후 4:48:51
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EtriCommandAgent
{

    /// <summary>
    /// There are no comments for EtriCommandAgent.TbCommand, EtriCommandAgent in the schema.
    /// </summary>
    public partial class TbCommand {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for TbCommand constructor in the schema.
        /// </summary>
        public TbCommand()
        {
            this.Ess1 = 0f;
            this.Ess2 = 0f;
            this.Ess3 = 0f;
            this.Ess4 = 0f;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Date in the schema.
        /// </summary>
        public virtual System.DateTime Date
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ess1 in the schema.
        /// </summary>
        public virtual float Ess1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ess2 in the schema.
        /// </summary>
        public virtual float Ess2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ess3 in the schema.
        /// </summary>
        public virtual float Ess3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ess4 in the schema.
        /// </summary>
        public virtual float Ess4
        {
            get;
            set;
        }
    }

}
