//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2019-10-08 오후 12:58:35
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace PEIU.Events.Alarm
{

    /// <summary>
    /// VIEW
    /// </summary>
    public partial class VwEventRecord {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for VwEventRecord constructor in the schema.
        /// </summary>
        public VwEventRecord()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for EventRecordId in the schema.
        /// </summary>
        public virtual int EventRecordId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DICode in the schema.
        /// </summary>
        public virtual int DICode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreateDT in the schema.
        /// </summary>
        public virtual System.DateTime CreateDT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for RecoveryDT in the schema.
        /// </summary>
        public virtual System.DateTime? RecoveryDT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AckDT in the schema.
        /// </summary>
        public virtual System.DateTime? AckDT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AckUserId in the schema.
        /// </summary>
        public virtual string AckUserId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SiteId in the schema.
        /// </summary>
        public virtual int SiteId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DeviceId in the schema.
        /// </summary>
        public virtual string DeviceId
        {
            get;
            set;
        }

    
        /// <summary>
        /// ??? ??
        /// 0 : ??
        /// 1 ~ 3 : ??
        /// 4 ~ : ??
        /// </summary>
        public virtual sbyte Level
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FactoryCode in the schema.
        /// </summary>
        public virtual int FactoryCode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for BitFlag in the schema.
        /// </summary>
        public virtual int BitFlag
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DeviceName in the schema.
        /// </summary>
        public virtual string DeviceName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }
    }

}
