//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2019-09-25 오후 1:13:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace PEIU.Events.Alarm
{

    /// <summary>
    /// There are no comments for PEIU.Events.Alarm.EventMap, EventModelLib in the schema.
    /// </summary>
    public partial class EventMap {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for EventMap constructor in the schema.
        /// </summary>
        public EventMap()
        {
            this.EventRecords = new HashSet<EventRecord>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for EventId in the schema.
        /// </summary>
        public virtual int EventId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Level in the schema.
        /// </summary>
        public virtual short Level
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Type in the schema.
        /// </summary>
        public virtual short Type
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Source in the schema.
        /// </summary>
        public virtual string Source
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        public virtual string Category
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EventRecords in the schema.
        /// </summary>
        public virtual ISet<EventRecord> EventRecords
        {
            get;
            set;
        }
    }

}
