//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2019-09-25 오후 1:13:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace PEIU.Events.Alarm
{

    /// <summary>
    /// There are no comments for PEIU.Events.Alarm.EventRecord, EventModelLib in the schema.
    /// </summary>
    public partial class EventRecord {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for EventRecord constructor in the schema.
        /// </summary>
        public EventRecord()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for EventRecordId in the schema.
        /// </summary>
        public virtual int EventRecordId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreateDT in the schema.
        /// </summary>
        public virtual System.DateTime CreateDT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for RecoveryDT in the schema.
        /// </summary>
        public virtual System.DateTime? RecoveryDT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AckDT in the schema.
        /// </summary>
        public virtual System.DateTime? AckDT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AckUserId in the schema.
        /// </summary>
        public virtual string AckUserId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SiteId in the schema.
        /// </summary>
        public virtual int SiteId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DeviceId in the schema.
        /// </summary>
        public virtual string DeviceId
        {
            get;
            set;
        }

        public virtual int EventId { get; set; }

        ///// <summary>
        ///// There are no comments for EventMap in the schema.
        ///// </summary>
        //public virtual EventMap EventMap
        //{
        //    get;
        //    set;
        //}
    }

}
