//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2019-10-08 오후 12:58:35
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace PEIU.Events.Alarm
{

    /// <summary>
    /// There are no comments for PEIU.Events.Alarm.DiMap, EventModelLib in the schema.
    /// </summary>
    public partial class DiMap {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for DiMap constructor in the schema.
        /// </summary>
        public DiMap()
        {
            this.Level = 4;
            this.EventRecords = new HashSet<EventRecord>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for DICode in the schema.
        /// </summary>
        public virtual int DICode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for BitFlag in the schema.
        /// </summary>
        public virtual int BitFlag
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GroupCode in the schema.
        /// </summary>
        public virtual int GroupCode
        {
            get;
            set;
        }

    
        /// <summary>
        /// ??? ??
        /// 0 : ??
        /// 1 ~ 3 : ??
        /// 4 ~ : ??
        /// </summary>
        public virtual sbyte Level
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DeviceName in the schema.
        /// </summary>
        public virtual string DeviceName
        {
            get;
            set;
        }

    
        ///// <summary>
        ///// There are no comments for ModbusFactory in the schema.
        ///// </summary>
        //public virtual ModbusFactory ModbusFactory
        //{
        //    get;
        //    set;
        //}

        public virtual int FactoryCode { get; set; }


        /// <summary>
        /// There are no comments for EventRecords in the schema.
        /// </summary>
        public virtual ISet<EventRecord> EventRecords
        {
            get;
            set;
        }
    }

}
